
    #include "Base/2D/NRE_Base2D.hpp"
    #include "Base/3D/NRE_Base3D.hpp"
    #include "Base/4D/NRE_Base4D.hpp"
    #include "Point/2D/NRE_Point2D.hpp"
    #include "Point/3D/NRE_Point3D.hpp"
    #include "Point/4D/NRE_Point4D.hpp"
    #include "Vector/NRE_Vector2D.hpp"
    #include "Matrix/NRE_Matrix2x2.hpp"
    #include "Vector/NRE_Vector3D.hpp"
    #include "Matrix/NRE_Matrix3x3.hpp"
    #include "Vector/NRE_Vector4D.hpp"
    #include "Matrix/NRE_Matrix4x4.hpp"
    #include "Plane/NRE_Plane.hpp"
    #include "Frustum/NRE_Frustum.hpp"
