BUFFEROBJECT = BufferObject
VAO = VAO
TEXTURE = Texture
SKYBOX = SkyBox

all : $(TARGET)

debug:
	@(cd $(BUFFEROBJECT) && $(MAKE))
	@(cd $(VAO) && $(MAKE))
	@(cd $(TEXTURE) && $(MAKE))
	@(cd $(SKYBOX) && $(MAKE))
