BUFFER = Buffer
BUFFEROBJECT = BufferObject
TEXTURE = Texture
SKYBOX = SkyBox

all : $(TARGET)

debug:
	@(cd $(BUFFER) && $(MAKE))
	@(cd $(BUFFEROBJECT) && $(MAKE))
	@(cd $(TEXTURE) && $(MAKE))
	@(cd $(SKYBOX) && $(MAKE))
