BRDF = BRDF
CAPTURE = Capture
GBUFFER = GBuffer
IRRADIANCE = Irradiance
PBR = PBR
PREFILTER = Prefilter
SKYBOX = SkyBox
SSAO = SSAO

all : $(TARGET)

debug:
	#@(cd $(BRDF) && $(MAKE))
	#@(cd $(CAPTURE) && $(MAKE))
	#@(cd $(GBUFFER) && $(MAKE))
	@(cd $(IRRADIANCE) && $(MAKE))
	@(cd $(PBR) && $(MAKE))
	@(cd $(PREFILTER) && $(MAKE))
	@(cd $(SKYBOX) && $(MAKE))
	#@(cd $(SSAO) && $(MAKE))
