WINDOW = Window
PIXELFORMAT = PixelFormat
SURFACE = Surface
EVENT = Event

all : $(TARGET)

debug:
	@(cd $(WINDOW) && $(MAKE))
	@(cd $(PIXELFORMAT) && $(MAKE))
	@(cd $(SURFACE) && $(MAKE))
	@(cd $(EVENT) && $(MAKE))
