VOXEL = Voxel
CHUNK = Chunk
MESH = Mesh
CHUNKCONSTRUCTOR = ChunkConstructor

all : $(TARGET)

debug:
	@(cd $(VOXEL) && $(MAKE))
	@(cd $(CHUNK) && $(MAKE))
	@(cd $(MESH) && $(MAKE))
	@(cd $(CHUNKCONSTRUCTOR) && $(MAKE))
