TIMESTEP = Timestep
DATE = Date
ADVDATE = AdvancedDate
CLOCK = Clock

all : $(TARGET)

debug:
	@(cd $(TIMESTEP) && $(MAKE))
	@(cd $(DATE) && $(MAKE))
	@(cd $(ADVDATE) && $(MAKE))
	@(cd $(CLOCK) && $(MAKE))
