COLOR = Color
SHADER = Shader
SSAO = SSAO
DEFERRED = DeferredRenderer

all : $(TARGET)

debug:
	@(cd $(COLOR) && $(MAKE))
	@(cd $(SHADER) && $(MAKE))
	@(cd $(SSAO) && $(MAKE))
	@(cd $(DEFERRED) && $(MAKE))
